### ISSUE TITLE
Support Ed25519

### ISSUE THREAD

**Issue by congngale** [kanidm/compact-jwt#5]
Hi @Firstyear,

I am working with some projects and found out that this repo could be a right fit for me, but It is lacking of supporting **Ed25519**. Do we have any plan for adding this algorithm in the near future?

Thanks,
Cong Nga Le

**Comment by Firstyear** [comment]
Hi there,

We had a similar issue with https://github.com/kanidm/webauthn-rs because of this. The issue is that openssl ed25519 support doesn't allow re-hydration of a private or public key from the "octet key pair" https://www.rfc-editor.org/rfc/rfc8152#section-8.2 and https://www.rfc-editor.org/rfc/rfc8152#section-13.2 . Similar issues exist for jws per https://www.rfc-editor.org/rfc/rfc8037.html which also defines these as OKPs.

This is what is preventing us from proceeding with ed25519 or ed448 support in both libraries. I could be wrong and openssl now supports this and I've missed that update, but last I looked, we were not able to support ed25519 in either library due to this. 

Does this help explain the situation? If it were possible I'd be happy to add ed25519 of course :)

**Comment by congngale** [comment]
@Firstyear , Thanks for your reply. I look forward to have ed25519 supported in the future.
